services:
    nodejs:
        image: node:24-alpine3.21
        volumes:
            - .:/www
        working_dir: /www
        ports:
            - 83:80
        command: sh -c "node ./demo/server.cjs"